name: architecture_template
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-382.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  flutter_mobx: ^2.0.6+5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  mobx_codegen: ^2.0.1+3
  json_annotation: ^4.0.1
  json_serializable: ^6.5.4




flutter:

  uses-material-design: true

  assets:
    - asset/lang/
    - asset/svg/
    - asset/image/
    - asset/lottie/
